CREATE DATABASE messaging;

USE messaging;

CREATE TABLE users (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE, 
  password VARCHAR(100) NOT NULL, 
  status VARCHAR(100) NOT NULL DEFAULT 'Hello there!' 
);

CREATE TABLE messages(
  id INT PRIMARY KEY AUTO_INCREMENT,
  message VARCHAR(1000) NOT NULL,
  sender INT NOT NULL,
  receiver INT NOT NULL,
  sent_at DATETIME DEFAULT NOW(),
  FOREIGN KEY (sender) REFERENCES users(id),
  FOREIGN KEY (receiver) REFERENCES users(id)
);
